In [5]:
import pandas as pd
import numpy as np
import math
import seaborn as sns
from scipy import stats
from matplotlib import pyplot as plt

%matplotlib inline

In [6]:
mev = pd.read_csv('mental health related emergency visit.csv')
mev.head(20)

                                                                                                                Mental Health related Emergency Department visits by Age (years) for Total mental health presentations and Persons
Age (years)        Presentation type                 Sex     Period Crude rate per 100,000 population LL 95% CI                                          UL 95% CI
11 years and under Total mental health presentations Persons 14/15  93.9                              88.4                                                    99.7
                                                             15/16  112.1                             106.1                                                  118.3
                                                             16/17  112.0                             106.1                                                  118.2
                                                             17/18  120.9                             114.8                                                  127.3
                                                             18/19  135.7                             129.2                                                  142.4
                                                             19/20  141.8                             135.1                                                  148.6
                                                             20/21  165.3                             158.1                                                  172.7
12-17 years        Total mental health presentations Persons 14/15  2,104.5                           2,066.0                                              2,143.6
                                                             15/16  2,297.8                           2,257.6                                              2,338.6
                                                             16/17  2,452.3                           2,410.8                                              2,494.4
                                                             17/18  2,552.6                           2,510.4                                              2,595.3
                                                             18/19  2,725.2                           2,681.8                                              2,769.1
                                                             19/20  2,748.1                           2,704.9                                              2,791.8
                                                             20/21  3,618.6                           3,569.5                                              3,668.2
18-24 years        Total mental health presentations Persons 14/15  2,384.2                           2,348.4                                              2,420.5
                                                             15/16  2,594.7                           2,557.5                                              2,632.4
                                                             16/17  2,680.0                           2,642.4                                              2,718.0
                                                             17/18  2,670.9                           2,633.6                                              2,708.5
                                                             18/19  2,851.7                           2,813.6                                              2,890.2

In [24]:
mental_health = []

In [ ]:
mental_health['ED_visit'] = mev

In [4]:
psy_distress = pd.read_csv('psychological distress by Kessler 10 categories.csv')
psy_distress.head(10)

                                                                       Psychological distress by Kessler 10 categories by Psychological distress, Period and Age (years)
Psychological distress           Period Age (years) Per cent LL 95% CI                                          UL 95% CI
Moderate level of psych distress 2020   16-24 years 33.4     28.3                                                    38.4
                                        25-34 years 29.0     24.4                                                    33.6
                                        35-44 years 31.1     26.6                                                    35.6
                                        45-54 years 25.9     22.2                                                    29.5
                                        55-64 years 22.6     19.3                                                    25.9
                                        65-74 years 19.7     17.0                                                    22.4
                                        75+ years   25.7     22.6                                                    28.7
                                 2019   16-24 years 33.9     29.3                                                    38.5
                                        25-34 years 27.6     23.6                                                    31.6

In [11]:
suic = pd.read_csv('suicide.csv')
suic.head()

                                                           Suicide
LHD        Period Rate per 100,000 population LL 95% CI  UL 95% CI
Sydney LHD 2007   10.1                        7.6             13.1
           2008   5.9                         4.1              8.4
           2009   8.5                         6.2             11.3
           2010   12.7                        9.9             15.9

In [7]:
surg_audit= pd.read_excel('Sample Surgical Audit Extract.xlsx')
surg_audit.head()

,MRN,SURNAME,FORENAME,GENDER,DTTM_OF_BIRTH,AGE,PRESENTING_PROBLEM,SPECIALTY_CODE,SPECIALTY_DESCRIPTION,BOOKING_CONSULTANT_NAME,...,CANCR_REASON,CANCEL_COMMENT,CANCELLATION_REASON,INTHEATRE_COMMENTS,FINANCIAL_CLASS,WAITING_LIST_CATEGORY,DAYS_ON_LIST,DEPENDANT_RESOURCES,HOSPITAL,THEATRE_CODE
0,3246359,A Dabel,Naser,M,09/12/1993,27,appendicitis,ASU,Acute Surgery,"Chen, Stan",...,NaN,NaN,NaN,NaN,M/C Ineligible Priv Dr,NaN,NaN,NaN,John Hunter Hospital,JHHOR11
1,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,"Davies, Allan",...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
2,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,"Davies, Allan",...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
3,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,"Davies, Allan",...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
4,419426,Abberfield,Sheree,F,29/03/1979,42,NaN,GE,Gastroenterology,"Foster, Robert",...,NaN,NaN,NaN,NaN,NaN,2-Within 90 days,76.0,NaN,John Hunter Hospital,RNCPRO3

In [6]:
surg_audit.dtypes

MRN                                  int64
SURNAME                             object
FORENAME                            object
GENDER                              object
DTTM_OF_BIRTH                       object
AGE                                  int64
PRESENTING_PROBLEM                  object
SPECIALTY_CODE                      object
SPECIALTY_DESCRIPTION               object
BOOKING_CONSULTANT_NAME             object
SECONDARY_SPECIALTY_DESCRIPTION    float64
SURGICAL_CONSULTANT_NAME            object
SECONDARY_CONSULTANT               float64
SURGEON_OPERATING_NAME              object
SURGICAL_ASSISTANT_1_NAME           object
ADMIT_DTTM                          object
DISCH_DTTM                          object
AMO_NAME                            object
AGSU_DISCHARGE_DTTM2                object
AGSU_DISCHARGE_SPECIALTY2           object
AGSU_DISCHARGE_PROCA2               object
AGSU_LOS2                          float64
LOS_HOURS                            int64
STAY_TYPE                           object
ADMISSION_TYPE                      object
REFERRAL_SOURCE                     object
REF_QCODE                           object
PREVIOUS_ADMIT_DTTM                 object
BOOKED_OP_DTTM                      object
SURGY_START_DTTM                    object
SURGY_CMPLT_DTTM                    object
PROCEDURE_CODE                       int64
PROCEDURE_DESCRIPTION               object
PROCEDURE_SORT                       int64
SCHDL_COMMENT                       object
CODE_COMMENT                        object
OPERATION_TYPE                      object
ACUTE_URGENCY_DESCRIPTION           object
CANCEL_DTTM                        float64
CANCR_REASON                       float64
CANCEL_COMMENT                     float64
CANCELLATION_REASON                float64
INTHEATRE_COMMENTS                  object
FINANCIAL_CLASS                     object
WAITING_LIST_CATEGORY               object
DAYS_ON_LIST                       float64
DEPENDANT_RESOURCES                 object
HOSPITAL                            object
THEATRE_CODE                        object
dtype: object

In [8]:
surg_audit.corr()

,MRN,AGE,SECONDARY_SPECIALTY_DESCRIPTION,SECONDARY_CONSULTANT,AGSU_LOS2,LOS_HOURS,PROCEDURE_CODE,PROCEDURE_SORT,CANCEL_DTTM,CANCR_REASON,CANCEL_COMMENT,CANCELLATION_REASON,DAYS_ON_LIST
MRN,1.000000,-0.559420,NaN,NaN,NaN,-0.191717,0.274160,0.302748,NaN,NaN,NaN,NaN,-1.000000
AGE,-0.559420,1.000000,NaN,NaN,NaN,0.649578,-0.402955,-0.334588,NaN,NaN,NaN,NaN,1.000000
SECONDARY_SPECIALTY_DESCRIPTION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SECONDARY_CONSULTANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGSU_LOS2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOS_HOURS,-0.191717,0.649578,NaN,NaN,NaN,1.000000,-0.149381,-0.332421,NaN,NaN,NaN,NaN,-1.000000
PROCEDURE_CODE,0.274160,-0.402955,NaN,NaN,NaN,-0.149381,1.000000,-0.107168,NaN,NaN,NaN,NaN,-0.984798
PROCEDURE_SORT,0.302748,-0.334588,NaN,NaN,NaN,-0.332421,-0.107168,1.000000,NaN,NaN,NaN,NaN,-0.484123
CANCEL_DTTM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CANCR_REASON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CANCEL_COMMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CANCELLATION_REASON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAYS_ON_LIST,-1.000000,1.000000,NaN,NaN,NaN,-1.000000,-0.984798,-0.484123,NaN,NaN,NaN,NaN,1.000000

In [9]:
surg_audit['WAITING_LIST_CATEGORY'].value_counts()

2-Within 90 days    7
Name: WAITING_LIST_CATEGORY, dtype: int64

In [10]:
surg_audit = surg_audit.reset_index()

In [11]:
surg_audit.columns = surg_audit.columns.str.lower()

In [12]:
surg_audit

,index,mrn,surname,forename,gender,dttm_of_birth,age,presenting_problem,specialty_code,specialty_description,...,cancr_reason,cancel_comment,cancellation_reason,intheatre_comments,financial_class,waiting_list_category,days_on_list,dependant_resources,hospital,theatre_code
0,0,3246359,A Dabel,Naser,M,09/12/1993,27,appendicitis,ASU,Acute Surgery,...,NaN,NaN,NaN,NaN,M/C Ineligible Priv Dr,NaN,NaN,NaN,John Hunter Hospital,JHHOR11
1,1,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
2,2,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
3,3,482552,Abberfield,Craig,M,15/03/1969,52,NSTEMI,CAR,Cardiology,...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,RNCISL1
4,4,419426,Abberfield,Sheree,F,29/03/1979,42,NaN,GE,Gastroenterology,...,NaN,NaN,NaN,NaN,NaN,2-Within 90 days,76.0,NaN,John Hunter Hospital,RNCPRO3
5,5,3234051,Abberton,Alysha,F,23/10/1997,23,Renal colic,URO,Urology,...,NaN,NaN,NaN,NaN,No Charge,NaN,NaN,NaN,John Hunter Hospital,JHHOR04
6,6,3234051,Abberton,Alysha,F,23/10/1997,23,Renal colic,URO,Urology,...,NaN,NaN,NaN,NaN,No Charge,NaN,NaN,NaN,John Hunter Hospital,JHHOR04
7,7,3234051,Abberton,Alysha,F,23/10/1997,23,Renal colic,URO,Urology,...,NaN,NaN,NaN,NaN,No Charge,NaN,NaN,NaN,John Hunter Hospital,JHHOR04
8,8,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
9,9,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
10,10,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
11,11,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
12,12,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
13,13,3234051,Abberton,Alysha,F,23/10/1997,23,rigid cystoscopy + right ureteroscopy +/- lith...,URO,Urology,...,NaN,NaN,NaN,NaN,Public Patient,2-Within 90 days,35.0,Radiology,John Hunter Hospital,JHHOR14
14,14,900134,Abbiss,Christopher,M,21/11/1980,40,bilateral knee laceration,ORT,Orthopaedics,...,NaN,NaN,NaN,NaN,Ch Shared On Call Dr,NaN,NaN,NaN,John Hunter Hospital,JHHOR09
15,15,1659206,Abbot,Shane,M,23/11/2002,18,Left ring finger wound washout + closure (local),ORT,Orthopaedics,...,NaN,NaN,NaN,NaN,W/Comp - NWAU,NaN,NaN,NaN,John Hunter Hospital,JHHOR02
16,16,1659206,Abbot,Shane,M,23/11/2002,18,Left ring finger wound washout + closure (local),ORT,Orthopaedics,...,NaN,NaN,NaN,NaN,W/Comp - NWAU,NaN,NaN,NaN,John Hunter Hospital,JHHOR02
17,17,2905469,Abbott,Jason,M,27/05/1968,53,# tibia MBC,ORT,Orthopaedics,...,NaN,NaN,NaN,DR PHILL DOBSON,Public Patient,NaN,NaN,NaN,John Hunter Hospital,JHHOR09
18,18,3127672,Abbott,Karen,F,03/09/1964,56,? foreign body,GE,Gastroenterology,...,NaN,NaN,NaN,NaN,Public Patient,NaN,NaN,NaN,John Hunter Hospital,JHHOR04

In [16]:
surg_audit.isnull().sum()

index                               0
mrn                                 0
surname                             0
forename                            0
gender                              0
dttm_of_birth                       0
age                                 0
presenting_problem                  1
specialty_code                      0
specialty_description               0
booking_consultant_name             0
secondary_specialty_description    19
surgical_consultant_name            4
secondary_consultant               19
surgeon_operating_name              4
surgical_assistant_1_name          14
admit_dttm                          0
disch_dttm                          0
amo_name                            1
agsu_discharge_dttm2               18
agsu_discharge_specialty2          18
agsu_discharge_proca2              18
agsu_los2                          18
los_hours                           0
stay_type                           0
admission_type                      1
referral_source                     1
ref_qcode                           1
previous_admit_dttm                 4
booked_op_dttm                      0
surgy_start_dttm                    0
surgy_cmplt_dttm                    0
procedure_code                      0
procedure_description               0
procedure_sort                      0
schdl_comment                       0
code_comment                        0
operation_type                      0
acute_urgency_description           7
cancel_dttm                        19
cancr_reason                       19
cancel_comment                     19
cancellation_reason                19
intheatre_comments                 18
financial_class                     1
waiting_list_category              12
days_on_list                       12
dependant_resources                13
hospital                            0
theatre_code                        0
dtype: int64

In [10]:
mh_age = pd.read_excel('age.xlsx')
mh_age.head()

,Prescription type,Prescription,Count,Age group,2013–14,2014–15,2015–16,2016–17,2017–18,2018–19,2019–20,Average annual \nchange (per cent)\n 2015–16 to 2019–20
0,Subsidised prescriptions,Antipsychotics (N05A),"Rate (per 1,000 population)",0–4 years,0.93510,0.92558,0.99694,0.97857,1.05861,1.09902,1.18689,4.45662
1,Subsidised prescriptions,Antipsychotics (N05A),"Rate (per 1,000 population)",5–11 years,16.30270,16.90685,17.83076,18.18038,19.65762,20.20833,19.97689,2.88202
2,Subsidised prescriptions,Antipsychotics (N05A),"Rate (per 1,000 population)",12–17 years,36.39089,36.06574,36.19579,35.84552,37.31220,37.72919,38.77485,1.73562
3,Subsidised prescriptions,Antipsychotics (N05A),"Rate (per 1,000 population)",18–24 years,76.51879,75.16565,75.26122,75.44658,75.22000,74.74253,78.07084,0.9205
4,Subsidised prescriptions,Antipsychotics (N05A),"Rate (per 1,000 population)",25–34 years,136.82208,134.35470,130.34581,125.91141,120.24176,117.40282,118.60651,-2.33187

In [11]:
mh_med_prac = pd.read_excel('med_prac.xlsx')
mh_med_prac.head()

,Prescription type,Prescription,Medical Practitioner,2005–06,2006–07,2007–08,2008–09,2009–10,2010–11,2011–12,2012–13,2013–14(b),2014–15,2015–16,2016–17,2017–18,2018–19,2019–20,Average annual \nchange (per cent)\n 2015–16 to 2019–20
0,Subsidised prescriptions,Antipsychotics (N05A),General practitioners,1425386.0,1546887.0,1752272.0,1952263.0,2092423.0,2231199.0,2399440.0,2545314.0,2733187.0,2794216.0,2828359.0,2863994.0,2867472.0,2760538.0,2522434.0,-2.82125
1,Subsidised prescriptions,Antipsychotics (N05A),Non-psychiatrist specialists,45472.0,47429.0,60039.0,65088.0,69300.0,70848.0,76693.0,81133.0,83703.0,85844.0,88020.0,90244.0,93628.0,93841.0,99950.0,3.22868
2,Subsidised prescriptions,Antipsychotics (N05A),Psychiatrists,389006.0,415192.0,459274.0,503753.0,548120.0,584105.0,626349.0,667129.0,702552.0,690989.0,681300.0,667758.0,646123.0,634665.0,594171.0,-3.36304
3,Subsidised prescriptions,Antipsychotics (N05A),Subtotal(g),1864192.0,2012600.0,2274100.0,2523337.0,2712245.0,2888797.0,3105798.0,3298031.0,3525742.0,3578253.0,3608636.0,3636162.0,3660415.0,3695652.0,3757345.0,1.01468
4,Subsidised prescriptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
mh = mh_age.join(mh_med_prac, how='left')

ValueError: columns overlap but no suffix specified: Index(['Prescription type', 'Prescription', '2014–15', '2015–16', '2016–17',
       '2017–18', '2018–19', '2019–20',
       'Average annual \nchange (per cent)\n 2015–16 to 2019–20'],
      dtype='object')